services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: socialsim4
      POSTGRES_USER: socialsim4
      POSTGRES_PASSWORD: socialsim4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    init: true
    stop_grace_period: 30s
    tmpfs:
      - /var/run/postgresql
    runtime: runc
    networks:
      - backend

  app:
    build:
      context: .
      args:
        # Hardcode the frontend base to /css/socialsim/ for Vite build
        FRONTEND_BASE_URL: /css/socialsim/
    environment:
      # Backend configuration
      SOCIALSIM4_DATABASE_URL: postgresql+psycopg://socialsim4:socialsim4@db:5432/socialsim4
      SOCIALSIM4_BACKEND_HOST: 0.0.0.0
      SOCIALSIM4_BACKEND_PORT: 8000
      SOCIALSIM4_JWT_SIGNING_KEY: please-change-me

      # App URLs and root-path (hardcoded to /css/socialsim)
      SOCIALSIM4_BACKEND_ROOT_PATH: /css/socialsim
      SOCIALSIM4_APP_BASE_URL: http://0.0.0.0:8090/css/socialsim

      # Frontend dist path inside the image
      SOCIALSIM4_FRONTEND_DIST_PATH: /app/frontend/dist

      # Optional admin bootstrap
      ADMIN_EMAIL: zjucss@outlook.com
      ADMIN_USERNAME: zjucss
      ADMIN_PASSWORD: zjucss107
      ADMIN_FULL_NAME: ""
      ADMIN_ORGANIZATION: ""
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8000"
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.settimeout(2); s.connect((\"127.0.0.1\",8000)); s.close()'" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    user: "1000:1000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
      - backend
    restart: unless-stopped
    init: true
    stop_grace_period: 30s
    runtime: runc

volumes:
  postgres_data:


networks:
  backend:
    internal: true
